Repository ConsenSys-Academy/Blockchain-Developer-Bootcamp, pull requests merged in 2021-09, with the labels that each got.

#63 Update index.html
  docs/S01-fundamentals/M0-intro/index.html
Labels: in progress

#68 82 QuestBook-Learn Solidity
  docs/S00-intro/L6-keeping-up/index.md
Labels: in progress

#98 proofreading fixes
  docs/S01-fundamentals/M3-ag-blockchain/L1-mental-model/index.html
Labels: check guidelines

#117 [S05a-defi/M6-oracles/L1/] Recommend new articles
  docs/S05a-defi/M6-oracles/L1/index.md
Labels: in progress

#93 Markup link bug in chapter 3
  docs/S03-smart-contracts/M4-design-patterns/L4-oracles/index.md
Labels: in progress, 24hrs
